### PR TITLE
Update to Packer 1.7.2

### PR DESCRIPTION
**Pull request by ganeshjp**
Packer 1.7.1 Changelog: https://github.com/hashicorp/packer/blob/v1.7.1/CHANGELOG.md#171-march-31-2021

### CODE REVIEW

**Comment by ganeshjp** [comment]
Looks like the test of installed packer version is failing because of this bug - https://github.com/hashicorp/packer/issues/10855. Not sure how to address.

**Comment by nywilken** [comment]
> Looks like the test of installed packer version is failing because of this bug - [hashicorp/packer#10855](https://github.com/hashicorp/packer/issues/10855). Not sure how to address.

Hi @ganeshjp apologies for this inconvenience. Issue 10855 has been resolved in Packer v1.7.2, which was released yesterday. Please try with the latest release of Packer and let us know if you run into any issues. Cheers.

**Comment by ganeshjp** [comment]
@nywilken Thanks for the update - I bumped it to v1.7.2 and that works fine.

**Comment by ganeshjp** [comment]
@StefanScherer can this be merged?

**Review by StefanScherer — COMMENTED** [review]
Cool! Thank you @ganeshjp  for the update to 1.7.2!
LGTM

**Pull request merged**
