### PR TITLE
Update Packer to 1.8.4

### PR DESCRIPTION
**Pull request by rgl**

### CODE REVIEW

**Comment by rgl** [comment]
Maybe change the appveyor project environment? Maybe to the `Visual Studio 2022` build worker image?

**Comment by StefanScherer** [comment]
When I saw this TLS error I thought of an too old PowerShell or this option that I always have to set. But I thought chocolatey handles this automatically.

I did a chick test PR to upgrade chocolatey to 1.2.0, but that doesn't seem to fix it. https://ci.appveyor.com/project/StefanScherer/choco-packer/builds/45233497

So maybe as you mentioned updating the build worker image itself. 🤔

**Comment by StefanScherer** [comment]
I'm going to move the pipeline over to GitHub Actions. It works over there. I'll open a new PR to trigger the GH actions workflow.

**Comment by StefanScherer** [comment]
Release pipeline on GH actions works fine, but now the verification on Chocolatey's side shows the same TLS error 😬 
https://gist.github.com/95b26f7aad698869c93b3db174216c79
I'll ping the Chocolatey team what we can do here. It really seems it's related to the supported TLS version of the underlying operating system/PowerShell. 🤔

**Comment by StefanScherer** [comment]
On a Windows 11 machine I can run `choco install -pre -version 1.8.4 packer` and have the new version installed without the TLS error.

**Pull request closed without merging**
